// <auto-generated />
using System;
using FusionBackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FusionBackEnd.Migrations
{
    [DbContext(typeof(AppDataDbContext))]
    partial class AppDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FusionBackEnd.Models.RateCard", b =>
                {
                    b.Property<int>("RateCardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RateCardID"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastUpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdateOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxYrExperience")
                        .HasColumnType("int");

                    b.Property<int>("MinYrExperienc")
                        .HasColumnType("int");

                    b.Property<double>("RatePerHrUSD")
                        .HasColumnType("float");

                    b.Property<Guid>("RateSkillID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillID1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RateCardID");

                    b.HasIndex("SkillID1");

                    b.ToTable("RateCards");
                });

            modelBuilder.Entity("FusionBackEnd.Models.Skill", b =>
                {
                    b.Property<Guid>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SSkill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillID");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("FusionBackEnd.Models.RateCard", b =>
                {
                    b.HasOne("FusionBackEnd.Models.Skill", "SkillID")
                        .WithMany()
                        .HasForeignKey("SkillID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkillID");
                });
#pragma warning restore 612, 618
        }
    }
}
